# Generated by Django 5.0.1 on 2024-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='type',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='user',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='dossierID',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medecin',
            name='medecinID',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.DecimalField(decimal_places=3, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='patientID',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='renderVousID',
            field=models.FloatField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tacheservice',
            name='tacheID',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
