# Generated by Django 5.0.1 on 2024-01-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_tacheservice_status_tacheservice_statust_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='id',
        ),
        migrations.RemoveField(
            model_name='medecin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tacheservice',
            name='id',
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='dossierID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='medecinID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='renderVousID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tacheservice',
            name='tacheID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
