# Generated by Django 5.0.1 on 2024-01-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_dossiermedical_dossierid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='dossierID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='medecinID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='renderVousID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='tacheservice',
            name='tacheID',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
