# Generated by Django 5.0.1 on 2024-01-24 20:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_dossiermedical_dossierid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
