# Generated by Django 5.0.1 on 2024-01-24 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_dossiermedical_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
