# Generated by Django 5.0.1 on 2024-01-25 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_patient_dossiermedical_patientid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(choices=[('en attente', 'en attente'), ('confirmé', 'confirmé')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='tacheservice',
            name='statusT',
            field=models.CharField(choices=[('en cours', 'en cours'), ('terminé', 'terminé')], default='1', max_length=20),
        ),
    ]
