# Generated by Django 5.0.1 on 2024-01-25 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_rendezvous_status_alter_tacheservice_statust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='status',
            field=models.CharField(choices=[('en attente', 'en attente'), ('confirmé', 'confirmé')], default='en attente', max_length=20),
        ),
        migrations.RemoveField(
            model_name='tacheservice',
            name='rendezvousID',
        ),
        migrations.AlterField(
            model_name='tacheservice',
            name='statusT',
            field=models.CharField(choices=[('en cours', 'en cours'), ('terminé', 'terminé')], default='en cours', max_length=20),
        ),
        migrations.AddField(
            model_name='tacheservice',
            name='rendezvousID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rendezvous'),
        ),
    ]
