# Generated by Django 5.0.1 on 2024-01-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_rendezvous_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacheservice',
            name='rendezvousID',
        ),
        migrations.AddField(
            model_name='tacheservice',
            name='rendezvousID',
            field=models.ManyToManyField(to='app.rendezvous'),
        ),
    ]
