# Generated by Django 5.0.1 on 2024-01-25 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_tacheservice_rendezvousid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tacheservice',
            name='rendezvousID',
        ),
        migrations.AddField(
            model_name='tacheservice',
            name='rendezvousID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.rendezvous'),
        ),
    ]
